### ISSUE TITLE
it -c i18n.config.js失败问题

### ISSUE THREAD

**Issue by hdtopku** [IFreeOvO/i18n-cli#145]
node 22 的版本还是会报错，降级到 18 也一样会报错！

```
> it -c ./i18n.config.js

(node:95740) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/lxh/.nvm/versions/node/v22.1.0/lib/node_modules/@ifreeovo/i18n-extract-cli/dist/utils/initConfig.js:20
            const config = require(configPath);
                           ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/lxh/Desktop/tiny-admin/tiny-admin-vue/i18n.config.js from /Users/lxh/.nvm/versions/node/v22.1.0/lib/node_modules/@ifreeovo/i18n-extract-cli/dist/utils/initConfig.js not supported.
i18n.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename i18n.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/lxh/Desktop/tiny-admin/tiny-admin-vue/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at getUserConfig (/Users/lxh/.nvm/versions/node/v22.1.0/lib/node_modules/@ifreeovo/i18n-extract-cli/dist/utils/initConfig.js:20:28)
    at getI18nConfig (/Users/lxh/.nvm/versions/node/v22.1.0/lib/node_modules/@ifreeovo/i18n-extract-cli/dist/utils/initConfig.js:33:24)
    at default_1 (/Users/lxh/.nvm/versions/node/v22.1.0/lib/node_modules/@ifreeovo/i18n-extract-cli/dist/core.js:247:53)
    at Command.<anonymous> (/Users/lxh/.nvm/versions/node/v22.1.0/lib/node_modules/@ifreeovo/i18n-extract-cli/dist/index.js:27:24)
    at Command.listener [as _actionHandler] (/Users/lxh/.nvm/versions/node/v22.1.0/lib/node_modules/@ifreeovo/i18n-extract-cli/node_modules/commander/lib/command.js:482:17) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v22.1.0

```

**Comment by IFreeOvO** [comment]
因为你项目`package.json`开启了es模块。需要把`i18n.config.js`文件名改成`i18n.config.cjs`。命令改成` it -c ./i18n.config.cjs`

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。
