### ISSUE TITLE
报错了   请帮忙看一下

### ISSUE THREAD

**Issue by zysgithub** [IFreeOvO/i18n-cli#27]

**Comment by IFreeOvO** [comment]
你可以定位到是哪个文件，具体哪行出错的吗，方便的话再截下图

**Comment by zysgithub** [comment]
正在转换中文，请稍等...
C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\types\lib\definitions\utils.js:112
    throw new TypeError(`Property ${key} of ${node.type} expected node to be of a type ${JSON.stringify(types)} but instead got ${JSON.stringify(val == null ? void 0 : val.type)}`);
          ^

TypeError: Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral","BigIntLiteral","DecimalLiteral","PrivateName"] but instead got "CallExpression"
    at validate (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\types\lib\definitions\utils.js:112:11)
    at Object.assign.oneOfNodeTypes [as validate] (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\types\lib\definitions\core.js:628:11)
    at validateField (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\types\lib\validators\validate.js:21:9)
    at validate (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\types\lib\validators\validate.js:15:3)
    at NodePath._replaceWith (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\replacement.js:132:5)
    at NodePath.replaceWith (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\replacement.js:118:8)
    at StringLiteral (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\dist\transformJs.js:135:30)
    at NodePath._call (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\context.js:45:20)
    at NodePath.call (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\context.js:35:17)
    at NodePath.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\context.js:80:31)
    at TraversalContext.visitQueue (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:107:19)
    at traverseNode (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:107:19)
    at traverseNode (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:107:19)
    at traverseNode (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\context.js:86:52)
    at TraversalContext.visitQueue (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\context.js:107:19)
    at traverseNode (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\traverse-node.js:18:17)
    at NodePath.visit (C:\Users\70360\AppData\Roaming\npm\node_modules\@ifreeovo\i18n-extract-cli\node_modules\@babel\traverse\lib\path\context.js:86:52)

**Comment by IFreeOvO** [comment]
你这样，运行指令时后面加个 -v   。可以打印出大概翻译哪个文件时出错。

**Comment by IFreeOvO** [comment]
可以加下Q群46847850。方便讨论

**Comment by zysgithub** [comment]
好的  我加群了   那个文件的问题也找到了

**Comment by zysgithub** [comment]
![image](https://user-images.githubusercontent.com/18143254/218027382-e84beccc-99e0-4176-a424-cf736f6fec84.png)

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。

**Comment by IFreeOvO** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

此 issue 已被自动锁定，因为关闭后没有任何近期活动。如果有相关 bug，请重新创建一个新 issue。
